services:
  backend:
    container_name: flask-backend
    image: flask-backend:v1.0.0
    ports:
      "5000:5000"
  environment:
    BACKEND_ENV=${BACKEND_ENV}
    SECRET_KEY=${SECRET_KEY}
    MONGO_URI_PROD=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@${MONGO_HOST}:27017/PROD_MONITOREAR?authSource=admin
    MONGO_URI_DEV=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@${MONGO_HOST}:27017/DEV_MONITOREAR?authSource=admin
    MONGO_URI_TEST=mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@${MONGO_HOST}:27017/TEST_MONITOREAR?authSource=admin
    
    PYTHONPATH=/code/src